version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    volumes:
      - "${ROOT}/config/plex/transcode:/tmp/Transcode"
      - "${ROOT}/config/plex/config:/config"
      - "${ROOT}/media:/data"
    ports:
      - 32400:32400/tcp
    environment:
      - VIRTUAL_HOST=plex.${VIRTUAL_HOST},advertise.plex.${VIRTUAL_HOST}:32400
      - VIRTUAL_PORT=32400
      - LETSENCRYPT_HOST=plex.${VIRTUAL_HOST}
      - TZ=Europe/Stockholm
      - PLEX_CLAIM=${PLEX_CLAIM}
      - HOSTNAME=plex.${VIRTUAL_HOST}
      - PUID=${MEDIA_UID}
      - PGID=${MEDIA_GID}
    restart: unless-stopped
    networks:
      - tier_1
      - tier_0
  gluetun:
    container_name: gluetun
    image: qmcgaw/gluetun
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - ${ROOT}/config/gluetun:/gluetun
    environment:
      - VPN_SERVICE_PROVIDER=custom #mullvad
      - VPN_TYPE=wireguard
      # can use the below when setting provider to mullvad
      # - SERVER_CITIES=Stockholm
      - VPN_ENDPOINT_IP=${WIREGUARD_ENDPOINT} # not needed with mullvad
      - VPN_ENDPOINT_PORT=${WIREGUARD_PORT} # not needed with mullvad
      - WIREGUARD_PUBLIC_KEY=${WIREGUARD_PUBLIC_KEY} # not needed with mullvad
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
    ports:
      - ${WIREGUARD_PORT}:${WIREGUARD_PORT}/udp
      - ${WIREGUARD_FORWARDED_PORT}:${WIREGUARD_FORWARDED_PORT}/tcp
      - ${WIREGUARD_FORWARDED_PORT}:${WIREGUARD_FORWARDED_PORT}/udp #56512
    networks:
      - tier_1
      - tier_2
  media:
    image: linuxserver/transmission
    volumes:
      - "${ROOT}/config/ts:/config"
      - "${ROOT}/media:/media"
      - "${ROOT}/media/torrents:/watch"
    environment:
      - PUID=${MEDIA_UID}
      - PGID=${MEDIA_GID}
      - TZ=Europe/Stockholm
    restart: unless-stopped
    network_mode: service:gluetun
  flood:
    image: jesec/flood
    user: 1046:1046
    restart: unless-stopped
    volumes:
      - ${ROOT}/config/flood:/config
      - ${ROOT}/media:/media
    environment:
      - VIRTUAL_HOST=flood.${PRIVATE_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=flood.${PRIVATE_VIRTUAL_HOST}
      - VIRTUAL_PORT=3000
    command: --allowedpath /media --auth default --host 0.0.0.0 --rundir /config
    networks:
      - tier_1
      - tier_2
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=${MEDIA_UID}
      - PGID=${MEDIA_GID}
      - TZ=Europe/Stockholm
      - VIRTUAL_HOST=radarr.${PRIVATE_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=radarr.${PRIVATE_VIRTUAL_HOST}
      - VIRTUAL_PORT=7878
    volumes:
      - ${ROOT}/config/radarr:/config
      - ${ROOT}/media:/media
    restart: unless-stopped
    networks:
      - tier_1
      - tier_2
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=${MEDIA_UID}
      - PGID=${MEDIA_GID}
      - TZ=Europe/Stockholm
      - VIRTUAL_HOST=sonarr.${PRIVATE_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=sonarr.${PRIVATE_VIRTUAL_HOST}
      - VIRTUAL_PORT=8989
    volumes:
      - ${ROOT}/config/sonarr:/config
      - ${ROOT}/media:/media
    restart: unless-stopped
    networks:
      - tier_1
      - tier_2
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - PUID=${MEDIA_UID}
      - PGID=${MEDIA_GID}
      - TZ=Europe/Stockholm
      - VIRTUAL_PORT=9696
      - VIRTUAL_HOST=prowlarr.${PRIVATE_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=prowlarr.${PRIVATE_VIRTUAL_HOST}
    volumes:
      - ${ROOT}/config/prowlarr:/config
    restart: unless-stopped
    networks:
      - tier_1
      - tier_2
  tautulli:
    image: tautulli/tautulli
    restart: unless-stopped
    environment:
      - PUID=${MEDIA_UID}
      - PGID=${MEDIA_GID}
      - TZ=Europe/Stockholm
      - VIRTUAL_HOST=tautulli.${PRIVATE_VIRTUAL_HOST}
      - LETSENCRYPT_HOST=tautulli.${PRIVATE_VIRTUAL_HOST}
      - VIRTUAL_PORT=8181
    volumes:
      - ${ROOT}/config/tautulli:/config
      - "${ROOT}/config/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro"
    depends_on:
      - plex
    networks:
      - tier_1
      - tier_2

networks:
  tier_0:
    name: network_tier_0
  tier_1:
    name: network_tier_1
  tier_2:
