version: '3'
services:
  plex:
    image: plexinc/pms-docker
    volumes:
      - '/mnt/data/transcode:/transcode'
      - '/mnt/data/plex/config/plex:/config'
      - '/mnt/data/media:/data'
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_PLEX}
      - VIRTUAL_PORT=32400
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL_PLEX}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST_PLEX}
      - TZ=ROME
      - PLEX_CLAIM=${PLEX_CLAIM}
      - HOSTNAME=${PLEX_HOSTNAME}
      - ADVERTISE_IP=${PLEX_ADVERTISE_IP}
    restart: always
    networks:
      - tier_1
      - tier_0
  media:
    image: linuxserver/transmission
    volumes:
      - '/mnt/data/plex/config/ts:/config'
      - '/mnt/data/media:/downloads'
      - '/mnt/data/plex/torrents:/watch'
    ports:
      - "51413:51413"
      - "51413:51413/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=ROME
    restart: always
    networks:
      - tier_2

  flood:
    image: jesec/flood
    user: 1000:1000
    volumes:
      - /mnt/data/plex/config/flood:/config
      - /mnt/data/media:/data
    environment:
      - VIRTUAL_HOST=${VIRTUAL_HOST_TS}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL_TS}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST_TS}
      - VIRTUAL_PORT=3000
    command: 
      --allowedpath /data --trurl http://media:9091/rpc/ --truser progress44 --trpass 12688abcd --auth default --host 0.0.0.0 --rundir /config
    networks:
      - tier_0
      - tier_1
      - tier_2


networks:
  tier_0:
    external:
      name: network_tier_0
  tier_1:
    external:
      name: network_tier_1
  tier_2: